obj-$(CONFIG_HDMI_SUNXI) += hdcp.o

hdcp-y					:= drv_hdmi.o
hdcp-y					+= dev_hdmi.o
hdcp-y					+= aw/hdmi_core.o
hdcp-y					+= aw/hdmi_core.o
hdcp-y					+= aw/hdmi_hal.o
hdcp-y					+= aw/hdmi_edid.o
hdcp-y					+= aw/hdmi_bsp_sun9iw1.o
hdcp-y					+= aw/hdmi_bsp_sun9iw1_table.o


