# Makefile for the Linux video drivers on sunxi platform.
# 16 Aug 2013, Tyle, <mailto:tyle@allwinnertech.com>
# Rewritten to use lists instead of if-statements.

obj-$(CONFIG_DISP2_SUNXI) += disp2/disp/
obj-$(CONFIG_HDMI_DISP2_SUNXI) += disp2/hdmi/
obj-$(CONFIG_DISP2_SUNXI) += disp2/tv/
